version: '2'
services:
    database:
        build: ./mariadb
        restart: always
#        volumes: # Set this line if you want to store mysql data outside of Container
#            - ./../Database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: aden
            MYSQL_DATABASE: aden
            MYSQL_USER: aden
            MYSQL_PASSWORD: aden
        networks:
            - backend

    php:
        build: ./php
        restart: always
        volumes:
            - ./web:/home/site/web
        links:
            - database
        networks:
            - backend

    server:
        build: ./nginx
        restart: always
        volumes:
            - ./web:/home/site/web
        links:
            - php
            - database
        networks:
            - frontend
            - backend

    server2:
        build: ./hhvm
        restart: always
        volumes:
            - ./web:/var/www/public
        links:
            - database
        networks:
            - frontend
            - backend

    proxy:
        build: ./varnish
        restart: always
        expose:
            - 8080
        environment:
            VARNISH_CONFIG: /etc/varnish/default.vcl
            CACHE_SIZE: 128m
            VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
            VARNISH_PORT: 8080
            BACKEND_HOST: server
            BACKEND_PORT: 8888
            VARNISH_SERVER: SERVER1
        links:
            - server
        networks:
            - frontend

    proxy2:
        build: ./varnish
        restart: always
        expose:
            - 8080
        environment:
            VARNISH_CONFIG: /etc/varnish/default.vcl
            CACHE_SIZE: 128m
            VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
            VARNISH_PORT: 8080
            BACKEND_HOST: server2
            BACKEND_PORT: 8888
            VARNISH_SERVER: SERVER2
        links:
            - server2
        networks:
            - frontend

    balancer:
        build: ./haproxy
        restart: always
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - proxy
            - proxy2
        networks:
            - frontend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
