proxy:
    build: ./varnish
    ports:
        - "8080:80"
    volumes:
        - ./varnish/default.vcl:/etc/varnish/default.vcl
    environment:
        - VCL_CONFIG=/etc/varnish/default.vcl
        - CACHE_SIZE=128m
        - VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600
    links:
        - server

server:
    build: ./nginx
    volumes:
        - ./web:/home/site/web
        - ./nginx/sites-enabled/site.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/sites-enabled/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/fastcgi_cache:/etc/nginx/fastcgi_cache
        - ./nginx/static_files.conf:/etc/nginx/static_files.conf
    links:
        - php

php:
    build: ./php
    volumes:
        - ./web:/home/site/web
    links:
        - database

database:
    build: ./mariadb
    environment:
        MYSQL_ROOT_PASSWORD: aden
        MYSQL_DATABASE: aden
        MYSQL_USER: aden
        MYSQL_PASSWORD: aden
